-- DoceCusto - banco do MVP acadêmico
-- Execute tudo no SQL Editor do Supabase.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null check (type in ('insumo','embalagem','gasto_indireto'))
);

create table if not exists public.cost_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint not null references public.categories(id) on delete restrict,
  base_price numeric(12,2) not null check (base_price >= 0),
  base_quantity numeric(12,3) not null check (base_quantity > 0),
  unit text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sale_price numeric(12,2),
  created_at timestamptz not null default now()
);

create table if not exists public.product_items (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  cost_item_id bigint not null references public.cost_items(id) on delete restrict,
  quantity numeric(12,3) not null check (quantity > 0),
  unit text not null
);

insert into public.categories (name, type) values
  ('Insumos','insumo'),
  ('Embalagens','embalagem'),
  ('Gastos indiretos','gasto_indireto')
on conflict (name) do nothing;

-- MVP sem autenticação: RLS habilitado e acesso controlado pelas policies abaixo.
alter table public.categories enable row level security;
alter table public.cost_items enable row level security;
alter table public.products enable row level security;
alter table public.product_items enable row level security;

drop policy if exists "anon categories" on public.categories;
create policy "anon categories" on public.categories for all to anon using (true) with check (true);

drop policy if exists "anon cost items" on public.cost_items;
create policy "anon cost items" on public.cost_items for all to anon using (true) with check (true);

drop policy if exists "anon products" on public.products;
create policy "anon products" on public.products for all to anon using (true) with check (true);

drop policy if exists "anon product items" on public.product_items;
create policy "anon product items" on public.product_items for all to anon using (true) with check (true);

grant select, insert, update, delete on public.categories to anon;
grant select, insert, update, delete on public.cost_items to anon;
grant select, insert, update, delete on public.products to anon;
grant select, insert, update, delete on public.product_items to anon;
grant usage, select on all sequences in schema public to anon;

-- Dados de teste opcionais:
-- insert into public.cost_items (name, category_id, base_price, base_quantity, unit)
-- select 'Chocolate', id, 35.00, 1000, 'g' from public.categories where type='insumo';
